name: Build Pull Request

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Pull Request
        run: cp -r demo/public out
      - name: Export Build
        uses: actions/upload-artifact@v2
        with:
          name: demo-site
          path: out
          retention-days: 1
